# Generated by Django 4.2.1 on 2023-05-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_passwd_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='username',
        ),
    ]
