# Generated by Django 4.2.1 on 2023-05-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_is_staff_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
