# Generated by Django 4.2.1 on 2023-05-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('modelName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vehicleType', models.CharField(max_length=100)),
                ('rentRatePerDay', models.IntegerField()),
                ('fuel', models.CharField(max_length=100)),
                ('number_of_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('licensePlateNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dateRented', models.DateField()),
                ('dateDue', models.DateField()),
                ('cno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('modelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('cno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('reserveDate', models.DateField()),
                ('endDate', models.DateField()),
                ('cno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentcar.user')),
                ('licensePlateNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.rentcar')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRented', models.DateField()),
                ('dateReturned', models.DateField()),
                ('payment', models.IntegerField()),
                ('cno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentcar.user')),
                ('licensePlateNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.rentcar')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionName', models.CharField(max_length=100)),
                ('licensePlateNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.rentcar')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reserve',
            constraint=models.UniqueConstraint(fields=('licensePlateNo', 'startDate'), name='unique_licensePlateNo_startDate_combination'),
        ),
        migrations.AddConstraint(
            model_name='previousrental',
            constraint=models.UniqueConstraint(fields=('licensePlateNo', 'dateRented'), name='unique_licensePlateNo_dateRented_combination'),
        ),
        migrations.AddConstraint(
            model_name='options',
            constraint=models.UniqueConstraint(fields=('licensePlateNo', 'optionName'), name='unique_licensePlateNo_optionName_combination'),
        ),
    ]
