# Generated by Django 4.2.1 on 2023-05-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0002_alter_previousrental_cno_alter_reserve_cno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
