# Generated by Django 4.2.1 on 2023-05-30 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentcar', '0006_alter_rentcar_cno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='cno',
        ),
        migrations.AddField(
            model_name='reserve',
            name='cn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
