# Generated by Django 4.2.1 on 2023-05-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0007_remove_reserve_cno_reserve_cn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='cn',
            new_name='cno',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='startDate',
            new_name='starDate',
        ),
    ]
