# Generated by Django 4.2.1 on 2023-05-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0008_rename_cn_reserve_cno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='starDate',
            new_name='startDate',
        ),
    ]
