# Generated by Django 4.2.1 on 2023-05-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0009_rename_stardate_reserve_startdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
