# Generated by Django 4.2.1 on 2023-05-30 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentcar', '0010_delete_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('reserveDate', models.DateField()),
                ('endDate', models.DateField()),
                ('cno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('licensePlateNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.rentcar')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reserve',
            constraint=models.UniqueConstraint(fields=('licensePlateNo', 'startDate'), name='unique_licensePlateNo_startDate_combination'),
        ),
    ]
