# Generated by Django 4.2.1 on 2023-06-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0011_reserve_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentcar',
            options={'ordering': ['licensePlateNo']},
        ),
    ]
